# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: LASSP Journal Club 
email: colin.clement@gmail.com 
description: > # this means to ignore newlines until "baseurl:"
    This website stores notes from short talks given to and presented
    by Cornell graduate students in the Physics department.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://colinclement.github.io/lasspjc" # the base hostname & protocol for your site
github_username: colin.clement

# Build settings
markdown: kramdown
